### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by kplimack** [iJanki/kubecron#6]
Can you please provide ARM support?
I see you are using `goreleaser`, which can perform a multi-arch build, produce releases and archives, and also produce a brew formula.  Would it be possible to hook all these things up to ease installation for your users?

**Comment by danielec7** [comment]
merged

**Comment by kplimack** [comment]
@iJanki would it still be possible to add the `brew` section of the .goreleaser.yml and setup github actions?

**Comment by danielec7** [comment]
Hi, I'm not actively developing this utility as it is mostly obsolete now since kubectl added the following way to run crons:

kubectl create job --from=cronjob/<name of cronjob> <name of job>

**Comment by kplimack** [comment]
TIL.  thank you!
